version: 2
name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install dependencies, build, and test
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      # Send coverage report to Coveralls
      - name: Upload coverage to Coveralls
        run: npx coveralls < coverage/lcov.info
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
