name: CI

on:
  pull_request: {}

env:
  PORT: ${{ secrets.PORT }}
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  JWT_SECRETKEY: ${{ secrets.JWT_SECRETKEY }}
  JWT_EXPIRE: ${{ secrets.JWT_EXPIRE }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
  API_KEY: ${{ secrets.API_KEY }}
  API_SECRET: ${{ secrets.API_SECRET }}
  MAIL_ID: ${{ secrets.MAIL_ID }}
  MP: ${{ secrets.MP }}
  SMTP_HOST: ${{ secrets.SMTP_HOST }}
  SMTP_HOST_PORT: ${{ secrets.SMTP_HOST_PORT }}
  ADMIN: ${{ secrets.ADMIN }}
  PASSWORD: ${{ secrets.PASSWORD }}
  BASE_URL: ${{ secrets.BASE_URL }}
  BASE_URL_ONLINE: ${{ secrets.BASE_URL_ONLINE }}
  BASE_URL_LOCAL: ${{ secrets.BASE_URL_LOCAL }}
  WRONG_TOKEN: ${{ secrets.WRONG_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      
      - name: Coveralls
      uses: coverallsapp/github-action@v2
